### ISSUE TITLE
REST API for Vajehh

### ISSUE THREAD

**Issue by 0ne-zero** [amir2mi/vajehh#5]
- Hi, have you thought about creating a REST API service for Vajehh? If you're eager, I can work on it. 
- I have in mind to use Go (Golang) for this, what do you think?

**Comment by amir2mi** [comment]
Hi @0ne-zero.
It sounds good to me to provide a public API for third-party applications or developers who are interested to work with this data.
Currently, there is a [Node.js REST API](https://vajehh.com/api/teyfi/%D8%B3%D9%84%D8%A7%D9%85) that I have created for Vajehh, though it is just for this domain and is not available for public usage, besides I'm not sure if I can afford such a thing by myself for larger users count, probably it needs more resources.

**Comment by 0ne-zero** [comment]
- Oh, I didn't know there was such a thing. 
- Anyway, certainly that's good thing you publish public API and whenever you feel costs are going up,Take maintenance costs.

**Comment by amir2mi** [comment]
Yes, it would be great. I will consider your insightful thoughts on this, thanks!
